### ISSUE TITLE
releases/humans.txt 404 Not Found

### ISSUE THREAD

**Issue by Krinkle** [simevidas/webplatformdaily-site#102]
1. <http://webplatformdaily.org/releases/2015-10-05>.
2. Open "Settings".
3. Follow `<a href="humans.txt" target="_blank">humans.txt</a>`.

Should probably include a leading slash (`/`), or traverse up first (`../`).

**Comment by simevidas** [comment]
Fixed, thanks.

…by removing that setting; it was a remnant of the past. I thought patrons would want to be explicitly mentioned like that, but *meh*.
