### ISSUE TITLE
Connection timeout / site is offline

### ISSUE THREAD

**Issue by simevidas** [simevidas/webplatformdaily-site#106]
**Workaround** for users who are experiencing the timeout: Since the issue is caused by the connect.sid value in the Cookie request header, you can visit the site using this url: http://direct.webplatformdaily.org. Sign in does not work with this URL, but at least you'll be able to view the latest release.

***

**The issue:** Lately, I've been having issues with the connection timing out when trying to access the website. The issue is related to the site's session cookie (named “connect.sid”). Interestingly, the issue goes away *temporarily* after restarting the server, meaning it only occurs after the app has been *running for some time*.

I've since changed my server code, so that this cookie is only set after successfully logging in to the site. This means that it only affects patrons that have successfully logged in, and then try to access the site at some later point.

**My server setup:** WPD is a Node.js web app. The code that manages sessions is functionally equivalent to this:

```js
var express = require('express');
var session = require('express-session');
var mongo = require('connect-mongo');

var app = express();
var MongoStore = mongo(session);

app.use(session({ 
	secret: process.env.SESSION_SECRET || '<fallback>',
	store: new MongoStore({ url: '<user:pass>@apollo.modulusmongo.net:27017/<id>' }),
	cookie: { maxAge: 1209600000 },
	resave: false,
	saveUninitialized: false
}));
```

Note: I've replaced the sensitive bits with tags like `<fallback>`, etc.

**Resolving the issue:** This setup has worked for a relatively long time without issue. At this point, I'm speculating what might be causing the timeout issue, i.e. **why does my app choke on the session cookie**. My server logs don't show any error in the logs (the timed-out request is logged normally like any other request).

I believe that the issue is due to the MongoDB database used with the app. I've recently switched to a newer database server (apollo.modulusmongo.net). I'm looking at the metrics on modulus.io, and it shows `0 ops/min`, meaning my app is not communicating with the database properly.

Again, the issue is temporarily resolved after restarting the app. I'll try to find out why my app can communicate with the database normally at first, but then causes timeouts after a few hours.

**Comment by simevidas** [comment]
Modulus Support has suggested switching to a database located at ‘Joyent US East’. I’ve performed this change, and I'm now waiting to see if the issue has been resolved.

**Comment by enapupe** [comment]
Doesn't look like..

> Unable to connect to any application instances.

**Comment by simevidas** [comment]
@enapupe Yes, I've just replied to Modulus. I've given them my own connect.sid cookie value, so they'll be able to reproduce the timeout, and hopefully find out what's causing this.

**Comment by enapupe** [comment]
Cool! I hope it works out. My days are incomplete without wpd :)

**Comment by simevidas** [comment]
There was some miscommunication with Modulus. Apparently, the database I switched to yesterday was still on the (older) Apollo server. I have just switched again, this time to the latest Olympia server. I've also cleared the sessions database, so all users should get new connect.sid cookies after signing in.

**Comment by simevidas** [comment]
It appears that the Olympia database server has "survived" so far (I hope this status update doesn't jinx it). I'll wait a few more days, and if there are no timeouts in that period, I'll report back to Modulus that there must be an issue with their older database servers.

**Comment by simevidas** [comment]
No timeouts since moving tyo Olympia. The issue must have been with the older database servers.
