### ISSUE TITLE
Persona.org to shut down by the end of this month

### ISSUE THREAD

**Issue by Krinkle** [simevidas/webplatformdaily-site#107]
![screen shot 2016-11-02 at 16 29 50](https://cloud.githubusercontent.com/assets/156867/19937535/97f7befa-a119-11e6-9c0e-c902e892ddfa.png)

More info:
<https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers>

**Comment by simevidas** [comment]
I think, I’ll switch to (email-based) passwordless authentication. Portier looks promising. 😄

**Comment by Krinkle** [comment]
Reminder, couple days left :)

**Comment by simevidas** [comment]
I can use [Passwordless](https://github.com/florianheinemann/passwordless). I’m trying to figure out if I can send tokens via a “token@webplatformdaily.org” email address, or if I would have to use my Gmail address or some other external email service. Web Platform Daily is a Node/Express app hosted on Modulus.io, and I’m not sure if there’s a Node module for sending out emails from my own domain.

**Comment by simevidas** [comment]
A bare-bones version of passwordless authentication is now available on the site. I’ll have to improve the UI, but the basic functionality should be there. Please report issues!

**Comment by simevidas** [comment]
I’ve tested throughout the evening; sometimes the token arrives after 5 seconds, other times it takes almost 10 minutes. It’s too early to tell what’s going on here (the provider is Mailgun and I’m using the mailgun-js module), but if you experience a longer delay, I’m interested to hear.

**Comment by simevidas** [comment]
> For newly allocated IPs, Mailgun protects and improves the reputation by gradually increasing sending rates. This means, as time passes, with high quality traffic, being sent from your IPs, your sending rates will increase automatically.

[Source](https://help.mailgun.com/hc/en-us/articles/203306890-I-just-submitted-a-lot-of-messages-Why-is-delivery-happening-so-slowly-).

I’ll check with my host (Modulus.io) if there is a problem with the reputation of their IP addresses.

There is also a [`o:deliverytime` field](http://blog.mailgun.com/tips-tricks-scheduling-email-delivery/) which may help - I’ll test.

**Comment by simevidas** [comment]
Mailgun’s support has responded; they’ve moved my IP to a less busy queue. I’ve tested a few times, and the emails were received instantaneously.

**Comment by simevidas** [comment]
Note to self: I just got signed out, despite visiting the site every day. I may have to investigate if the Passwordless server module edits the session cookies’ expiry somehow.
