### ISSUE TITLE
webplatform.news is down

### ISSUE THREAD

**Issue by G0dwin** [simevidas/webplatformdaily-site#109]
Hi @simevidas, it looks as though the site is down:

![image](https://cloud.githubusercontent.com/assets/1109252/25537909/5a2c0cb8-2bf5-11e7-8aea-9c2e9cf0bb4a.png)

**Comment by simevidas** [comment]
Yes, my host Xervo shut down. I’ll migrate to a new host today 😅

**Comment by G0dwin** [comment]
Closing since the site has been back up again for a few days. Šime, feel free to re-open if there are lingering tasks that you would like to keep track of here, and thanks for everything you do!
