### ISSUE TITLE
RSS feed for new design

### ISSUE THREAD

**Issue by jryans** [simevidas/webplatformdaily-site#110]
Is some kind of RSS / Atom / JSON Feed support planned for the new design? I haven't noticed it so far.

(I'll likely stop contributing if it's not planned, as I can't really consume information that updates this frequently unless I can add it to my feed reader.)

Thanks for all the work you do collating content for the site! 😁

**Comment by jryans** [comment]
The new [JSON Feed](https://jsonfeed.org/version/1) standard might be the easiest to add, depending on how your setup works.

**Comment by simevidas** [comment]
I can add an RSS feed, but its entries would only contain links to the issues (since the content is behind a login and cannot be included in a public feed). Would that suffice?

**Comment by jryans** [comment]
Well, in my view, it would be ideal to have the full content, but I realize that's quite a bit more complex when there's a login involved.

What about if the feed included a link to the issue and just the headings from the content? (Not sure if you are comfortable with having that publicly available.) Then I would have some idea what the issue is about, without revealing everything.

If it were possible to receive the full issue via email, that would also work for me, as I can pipe [email newsletters](http://blog.newsblur.com/post/146752875548/newsletters-in-your-newsblur) into my feed reader (NewsBlur).

**Comment by simevidas** [comment]
Regarding RSS, great news! I forgot to think about this earlier, but the way the new issues are structured, the title and first paragraph of each entry is public forever, so I can just include them in the RSS with “Read the rest on the website” links at the end of each entry. I’ll add this to my weekend todos.

Regarding email, I’d like to implement it using an API. Before, I used Mailchimp’s web interface but I grew tired of that 😅. From my experience, learning and setting up a new API can take a while, so I’m not sure when this will happen.

**Comment by jryans** [comment]
> Regarding RSS, great news! I forgot to think about this earlier, but the way the new issues are structured, the title and first paragraph of each entry is public forever, so I can just include them in the RSS with “Read the rest on the website” links at the end of each entry. I’ve added this to my weekend todos.

Great, seems like there is a path forward here! I'm glad to hear it's on your list. 😁 

> Regarding email, I’d like to implement it using an API. Before, I used Mailchimp’s web interface but I grew tired of that 😅. From my experience, learning and setting up a new API can take a while, so I’m not sure when this will happen.

Right, totally understand... email is painful for many different reasons. 😭

**Comment by birtles** [comment]
I'd really rather not have to get into RSS just for this so +1 for tackling email.

**Comment by jryans** [comment]
Seems like daily emails started appearing in the last few days, thanks! This method is sufficient for my needs. 😁

**Comment by simevidas** [comment]
Yup, and the RSS feed is here: https://webplatform.news/feed.xml

Let me know if there are any problems with it.

**Comment by jryans** [comment]
Great, thanks! I'll close this since it seems to be fixed now.
