### ISSUE TITLE
Oldest entry shows previous button, not next

### ISSUE THREAD

**Issue by sanand0** [simevidas/webplatformdaily-site#99]
A very minor point, but just thought I'd flag it. http://webplatformdaily.org/releases/2013-07-08 -- the earliest entry (I think) has a disabled "Next" button, whereas "Previous" is enabled. Perhaps you meant to do the opposite?

![image](https://cloud.githubusercontent.com/assets/63734/6369266/94780612-bd0a-11e4-9c49-bcabbbe2df8f.png)

**Comment by simevidas** [comment]
Yup, it’s a bug :) Thanks for reporting.

**Comment by simevidas** [comment]
Fixed :)
